// src/lib/components/pages/share/ShareCard.svelte
<script lang="ts">
	import { cn } from '$lib/utils'
	import StarRating from '../StarRating.svelte'
	import type { Share } from './GridView.svelte'

	/** 分享卡片（移植自旧站 src/app/share/components/share-card.tsx） */
	let { share }: { share: Share } = $props()

	let expanded = $state(false)
	let shown = $state(false)
	let cardEl = $state<HTMLElement | null>(null)

	const tags = $derived(share.tags ?? [])
	const initial = $derived((share.name || '?').trim().charAt(0))

	// 旧站用 motion 的 whileInView（移动端直接 animate）做入场，这里统一用 IntersectionObserver + CSS 过渡
	$effect(() => {
		if (!cardEl) return
		if (typeof IntersectionObserver === 'undefined') {
			shown = true
			return
		}

		const observer = new IntersectionObserver(
			entries => {
				if (entries.some(entry => entry.isIntersecting)) {
					shown = true
					observer.disconnect()
				}
			},
			{ rootMargin: '0px 0px -10% 0px' }
		)

		observer.observe(cardEl)
		return () => observer.disconnect()
	})
</script>

<!-- card utility 自带 absolute（首页卡片用），这里跟旧站一样用 relative 变回文档流 -->
<div bind:this={cardEl} class="card card-anim group relative! block overflow-hidden" data-shown={shown}>
	<div>
		<div class="mb-4 flex items-center gap-4">
			<div class="group relative">
				{#if share.logo}
					<img src={share.logo} alt={share.name} class="h-16 w-16 rounded-xl object-cover" />
				{:else}
					<!-- logo 缺失（历史数据里出现过 blob: 临时地址）时退化为首字母占位，避免裂图 -->
					<div class="bg-secondary/10 text-secondary flex h-16 w-16 items-center justify-center rounded-xl text-xl font-bold">
						{initial}
					</div>
				{/if}
			</div>
			<div class="flex-1">
				<h3 class="group-hover:text-brand text-lg font-bold transition-colors">{share.name}</h3>
				<a
					href={share.url}
					target="_blank"
					rel="noopener noreferrer"
					class="text-secondary hover:text-brand mt-1 block max-w-[200px] truncate text-xs hover:underline">
					{share.url}
				</a>
			</div>
		</div>

		<StarRating stars={share.stars ?? 0} />

		<div class="mt-3 flex flex-wrap gap-1.5">
			{#each tags as tag (tag)}
				<span class="bg-secondary/10 rounded-full px-2.5 py-0.5 text-xs">{tag}</span>
			{/each}
		</div>

		<button type="button" onclick={() => (expanded = !expanded)} class="mt-3 block w-full text-left">
			<p
				class={cn(
					'text-sm leading-relaxed text-gray-600 transition-all duration-300',
					expanded ? 'line-clamp-none' : 'line-clamp-3'
				)}>
				{share.description}
			</p>
		</button>
	</div>
</div>

// src/app/share/components/share-card.tsx
'use client'

import { motion } from 'motion/react'
import StarRating from '@/components/star-rating'
import { useSize } from '@/hooks/use-size'
import { cn } from '@/lib/utils'
import EditableStarRating from '@/components/editable-star-rating'
import { useState } from 'react'
import LogoUploadDialog, { type LogoItem } from './logo-upload-dialog'

export interface Share {
	name: string
	logo: string
	url: string
	description: string
	tags: string[]
	stars: number
}

interface ShareCardProps {
	share: Share
	isEditMode?: boolean
	onUpdate?: (share: Share, oldShare: Share, logoItem?: LogoItem) => void
	onDelete?: () => void
}

export function ShareCard({ share, isEditMode = false, onUpdate, onDelete }: ShareCardProps) {
	const [expanded, setExpanded] = useState(false)
	const [isEditing, setIsEditing] = useState(false)
	const { maxSM } = useSize()
	const [localShare, setLocalShare] = useState(share)
	const [showLogoDialog, setShowLogoDialog] = useState(false)
	const [logoItem, setLogoItem] = useState<LogoItem | null>(null)

	const handleFieldChange = (field: keyof Share, value: any) => {
		const updated = { ...localShare, [field]: value }
		setLocalShare(updated)
		onUpdate?.(updated, share, logoItem || undefined)
	}

	const handleLogoSubmit = (logo: LogoItem) => {
		setLogoItem(logo)
		const logoUrl = logo.type === 'url' ? logo.url : logo.previewUrl
		const updated = { ...localShare, logo: logoUrl }
		setLocalShare(updated)
		onUpdate?.(updated, share, logo)
	}

	const handleTagsChange = (tagsStr: string) => {
		const tags = tagsStr
			.split(',')
			.map(t => t.trim())
			.filter(t => t)
		handleFieldChange('tags', tags)
	}

	const handleCancel = () => {
		setLocalShare(share)
		setIsEditing(false)
		setLogoItem(null)
	}

	const canEdit = isEditMode && isEditing

	return (
		<motion.div
			initial={{ opacity: 0, scale: 0.6 }}
			{...(maxSM ? { animate: { opacity: 1, scale: 1 } } : { whileInView: { opacity: 1, scale: 1 } })}
			className='card relative block overflow-hidden'>
			{isEditMode && (
				<div className='absolute top-3 right-3 z-10 flex gap-2'>
					{isEditing ? (
						<>
							<button onClick={handleCancel} className='rounded-lg px-2 py-1.5 text-xs text-gray-400 transition-colors hover:text-gray-600'>
								取消
							</button>
							<button onClick={() => setIsEditing(false)} className='rounded-lg px-2 py-1.5 text-xs text-blue-400 transition-colors hover:text-blue-600'>
								完成
							</button>
						</>
					) : (
						<>
							<button onClick={() => setIsEditing(true)} className='rounded-lg px-2 py-1.5 text-xs text-blue-400 transition-colors hover:text-blue-600'>
								编辑
							</button>
							<button onClick={onDelete} className='rounded-lg px-2 py-1.5 text-xs text-red-400 transition-colors hover:text-red-600'>
								删除
							</button>
						</>
					)}
				</div>
			)}

			<div>
				<div className='mb-4 flex items-center gap-4'>
					<div className='group relative'>
						{localShare.logo ? (
							<img
								src={localShare.logo}
								alt={localShare.name}
								className={cn('h-16 w-16 rounded-xl object-cover', canEdit && 'cursor-pointer')}
								onClick={() => canEdit && setShowLogoDialog(true)}
							/>
						) : (
							// logo 缺失（历史数据里出现过 blob: 临时地址）时退化为首字母占位，避免裂图
							<div
								className={cn(
									'bg-secondary/10 text-secondary flex h-16 w-16 items-center justify-center rounded-xl text-xl font-bold',
									canEdit && 'cursor-pointer'
								)}
								onClick={() => canEdit && setShowLogoDialog(true)}>
								{(localShare.name || '?').trim().charAt(0)}
							</div>
						)}
						{canEdit && (
							<div className='ev pointer-events-none absolute inset-0 flex items-center justify-center rounded-xl bg-black/40 opacity-0 transition-opacity group-hover:opacity-100'>
								<span className='text-xs text-white'>更换</span>
							</div>
						)}
					</div>
					<div className='flex-1'>
						<h3
							contentEditable={canEdit}
							suppressContentEditableWarning
							onBlur={e => handleFieldChange('name', e.currentTarget.textContent || '')}
							className={cn('group-hover:text-brand text-lg font-bold transition-colors focus:outline-none', canEdit && 'cursor-text')}>
							{localShare.name}
						</h3>
						{canEdit ? (
							<div
								contentEditable
								suppressContentEditableWarning
								onBlur={e => handleFieldChange('url', e.currentTarget.textContent || '')}
								className='text-secondary mt-1 block max-w-[200px] cursor-text truncate text-xs focus:outline-none'>
								{localShare.url}
							</div>
						) : (
							<a
								href={localShare.url}
								target='_blank'
								rel='noopener noreferrer'
								className='text-secondary hover:text-brand mt-1 block max-w-[200px] truncate text-xs hover:underline'>
								{localShare.url}
							</a>
						)}
					</div>
				</div>

				{canEdit ? (
					<EditableStarRating stars={localShare.stars} editable={true} onChange={stars => handleFieldChange('stars', stars)} />
				) : (
					<StarRating stars={localShare.stars} />
				)}

				<div className='mt-3 flex flex-wrap gap-1.5'>
					{canEdit ? (
						<input
							type='text'
							value={localShare.tags.join(', ')}
							onChange={e => handleTagsChange(e.target.value)}
							placeholder='标签，用逗号分隔'
							className='w-full rounded-md border border-gray-300 bg-gray-50 px-2 py-1 text-xs focus:outline-none'
						/>
					) : (
						localShare.tags.map(tag => (
							<span key={tag} className='bg-secondary/10 rounded-full px-2.5 py-0.5 text-xs'>
								{tag}
							</span>
						))
					)}
				</div>

				<p
					contentEditable={canEdit}
					suppressContentEditableWarning
					onBlur={e => handleFieldChange('description', e.currentTarget.textContent || '')}
					onClick={e => {
						if (!canEdit) {
							e.preventDefault()
							setExpanded(!expanded)
						}
					}}
					className={cn(
						'mt-3 text-sm leading-relaxed text-gray-600 transition-all duration-300 focus:outline-none',
						canEdit ? 'cursor-text' : 'cursor-pointer',
						!canEdit && (expanded ? 'line-clamp-none' : 'line-clamp-3')
					)}>
					{localShare.description}
				</p>
			</div>

			{canEdit && showLogoDialog && <LogoUploadDialog currentLogo={localShare.logo} onClose={() => setShowLogoDialog(false)} onSubmit={handleLogoSubmit} />}
		</motion.div>
	)
}
